version: '3.4'

services:
  server3:
    image: server3
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ".:/usr/src/app"
    ports:
      - 3000:3000
      - 9230:9230
    command: ["node", "--inspect=0.0.0.0:9230", "./bin/www"]
