version: '3.4'

services:
  server2:
    image: server2
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: 4002
      NODE_ENV: production
    ports:
      - 4002:4002
