version: '3.4'

services:
  server1:
    image: server1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: 4001
      NODE_ENV: production
    ports:
      - 4001:4001
