version: '3.4'

services:
  server1:
    image: server1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: 3001
      NODE_ENV: development
    volumes:
      - ".:/usr/src/app"
    ports:
      - 3001:3001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./bin/www"]
